apiVersion: v1
kind: ConfigMap
metadata:
  name: incident-app-config
  namespace: incident-platform
data:
  MONGODB_URI: mongodb://mongo:27017/
  MONGODB_DB_NAME: incident_platform
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_USERNAME: ""
  REDIS_SSL: "false"
  RATE_LIMIT_REQUESTS: "30"
  RATE_LIMIT_WINDOW_SECONDS: "60"
